### ISSUE TITLE
.

### ISSUE THREAD

**Issue by taranehabd** [Bardiafa/Proxy-Checker#2]

**Comment by Bardiafa** [comment]
Hi , What is the problem ? 😊

**Comment by taranehabd** [comment]
سلام :)
کلا طرز استفادشون رو میشه بگید
یه بات اینستا با پایتون میخواستم بزنم بعد چون تو ایران فیلتر شده کار نمیده
حتی با وی پی ان. میتونم از اینا استفاده کنم و چجوری؟
ببخشید

در تاریخ چهارشنبه ۲۶ آوریل ۲۰۲۳،‏ ۱۲:۴۹ Barry Far ***@***.***>
نوشت:

**Comment by Bardiafa** [comment]
سلام
میتونید لینک RAW فایل proxies.txt رو به کد تون اضافه کنید که ابتدا فتچ کنه بعد به عنوان پروکسی ازش استفاده کنه.


برای نحوه پیاده کردن اونکار از هوش های مصنوعی موجود میتونید استفاده کنید که براتون انجام بده :) (حتماْ از راهنمایی های من بهتره)

**Comment by taranehabd** [comment]
خیلی ممنون :)

در تاریخ جمعه ۲۸ آوریل ۲۰۲۳،‏ ۰۰:۱۴ Barry Far ***@***.***>
نوشت:
